### ISSUE TITLE
The polyfill should respect margin-box

### ISSUE THREAD

**Issue by zhorvath** [adobe-webplatform/css-shapes-polyfill#1]
Currently the this test fails: 
https://github.com/adobe-webplatform/css-shapes-polyfill/blob/6dbafa40ee47d107826a55e848e0075fe28d1d2f/tests/shape-info-tests.js#L47

**Comment by betravis** [comment]
Should be fixed with
27b1868 

Problem was that the rectangles used for intersections were relative to the border box, not themselves ('margin-box' should have x and y coordinates at 0).
