### ISSUE TITLE
shape-outside: content-box with padding wraps around padding box

### ISSUE THREAD

**Issue by zhorvath** [adobe-webplatform/css-shapes-polyfill#2]
Failing test case:
https://github.com/adobe-webplatform/css-shapes-polyfill/commit/ae11b971edb52bcb35a5bb98e1eb9a27b72088e4

**Comment by betravis** [comment]
Should be fixed with
1b9b3f6

If a line and shape are coincident, they avoid each other (an intersection is marked even if the line ends at 20px and the shape begins there). So I tweaked the test a little to avoid the coincident lines.
